### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by drfeinberg** [audacitorch/audacity#68]
**Is your feature request related to a problem? Please describe.**
I would love linux support.

**Describe the solution you'd like**
binaries, deb/rpm, or even a .tar.gz

**Describe alternatives you've considered**
I looked at the installation instructions and it's quite complicated.

**Additional context**
Please and thank you.

**Comment by hugofloresgarcia** [comment]
Hi! Yes, I am working on this. The model manager UI is being a little finicky with Linux. Expect a Linux version within the next week or two.

**Comment by drfeinberg** [comment]
Amazing! Thanks!!!!

**Comment by hugofloresgarcia** [comment]
Update: The deep learning features have been working on Linux since fe360e9404443cd6e095eb42b56f0d171bcc348d, but we have not yet been able to get the GitHub workflows to create the AppImage properly. 

While this gets fixed, Audacity can be built  with deep learning from source in Linux distributions.
